### PR TITLE
Trunk improvements

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
Now Trunk is somewhat competitive with L-BFGS. At least on the test problem it does much better: https://travis-ci.org/JuliaSmoothOptimizers/Optimize.jl/jobs/159768840#L1248
@vepiteski

**Comment by abelsiqueira** [comment]
You said to merge more than one commit with the `create a merge commit`, but this is saying that it's not enabled for this repository.

**Comment by dpo** [comment]
Sorry. It is now.

**Comment by abelsiqueira** [comment]
Thank you

**Pull request merged**
