### PR TITLE
Augmented Lagrangian implementation

### PR DESCRIPTION
**Pull request by abelsiqueira**
Implementation of Augmented Lagrangian. Work in progress.

### CODE REVIEW

**Comment by dpo** [comment]
Let's revisit this once TRON is working. Should we find better names than TRON and AUGLAG?

**Comment by dpo** [comment]
There's a lot of stuff that's not related to the augmented Lagrangian in here. Would you mind revisiting this? Now that we have TRON, we should be able to write a general solver! I would also suggest writing a subtype of `AbstractNLPModel` to define the augmented Lagrangian subproblem, in the vein of [this (untested) example](https://github.com/JuliaSmoothOptimizers/AmplNLReader.jl/issues/39#issuecomment-283375906).

**Comment by abelsiqueira** [comment]
Yes, I was tinkering with this on top of the old #35, and actually I prefer to do this after #35, and possibly MADS, that I'm working on parallel.

**Comment by abelsiqueira** [comment]
Made some updates, still on top of #35, and not ready to merge.

**Comment by abelsiqueira** [comment]
Will rework this after #35

**Pull request closed without merging**
