### PR TITLE
Jpd func

### PR DESCRIPTION
**Pull request by vepiteski**
Switch from Symbol to Function to pass solvers as parameters

### CODE REVIEW

**Comment by dpo** [comment]
Could you please remove L-BFGS-B from here?

**Comment by vepiteski** [comment]
@dpo Sure, I forgot to remove L-BFGS-B. I don't know how to remove it...

**Comment by dpo** [comment]
@vepiteski See #29, which overlaps with this pull request. Should I just add the missing features there (for example, printing the solver name)?

**Comment by vepiteski** [comment]
@dpo Yes. Print solvers name, return stats and profile (for eventual reuse).

**Comment by dpo** [comment]
Ok, I'll close this now that it's all in #29.

**Pull request closed without merging**
