### PR TITLE
Line model counters

### PR DESCRIPTION
**Pull request by abelsiqueira**
Fixes #46

### CODE REVIEW

**Comment by dpo** [comment]
Needs rebasing?

**Comment by abelsiqueira** [comment]
It was using the `develop` branch of `Krylov`. Fixed now.

**Comment by dpo** [comment]
Somehow the `@unix CUTEst` in `test/REQUIRE` isn't honored on Windows.

**Comment by dpo** [comment]
The issue is that there's a `using CUTEst` in `test/solvers/tron.jl`.

**Comment by abelsiqueira** [comment]
> Somehow the @unix CUTEst in test/REQUIRE isn't honored on Windows

It looks like the tests on tron are using CUTEst. Let me make a PR fixing it.

**Comment by dpo** [comment]
Please rebase.

**Pull request merged**
