### PR TITLE
trunk: adjust cg stopping tolerances

### LINKED ISSUE #40: Trunk cgtol
`cgtol` should be proportional to the square root of the gradient norm and used as relative tolerance. Benchmark.

### PR DESCRIPTION
**Pull request by dpo**
closes #40

### CODE REVIEW

**Comment by abelsiqueira** [comment]
I think this needs `brew update && brew install gcc` on travis.

**Comment by dpo** [comment]
ps: updated performance profile generated from `two_solvers()`:

trunk-lbfgs

**Comment by dpo** [comment]
https://github.com/JuliaPackaging/Homebrew.jl/issues/212

**Comment by abelsiqueira** [comment]
Given the comparison, it's safe to say it's working. Thanks.

**Pull request merged**
