### PR TITLE
Introduce logging

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by abelsiqueira** [comment]
I'm not sure how the logging is supposed to be used. Is it to be created when calling the optimizer, outside Optimize.jl - like the examples? Also, `lbfgslogger` is inside `lbfgs.jl`, but `trunklogger` is not inside `trunk.jl`.

**Comment by dpo** [comment]
There it is. Sorry for the confusion. Yes, logging is supposed to be set up as in the examples. It's turned off by default but it's more flexible than a `verbose` argument that has to be propagated.

**Comment by dpo** [comment]
Same old gcc error. I think this can safely be labeled as good to go.

**Comment by abelsiqueira** [comment]
Manually rebased. Thanks.

**Pull request closed without merging**
