### PR TITLE
Call finalize on bmark_solvers to handle CUTEst problems

### PR DESCRIPTION
**Pull request by abelsiqueira**

### CODE REVIEW

**Comment by abelsiqueira** [comment]
This fails on 0.4 because I use the generator syntax. It's the only way to make it work with CUTEst because we can't open more than one problem at the same time.

**Comment by dpo** [comment]
The generator expression syntax `(...)` wasn't available in Julia 0.4, but we could still implement a generator as follows:
```julia
function cutest_problems(names :: Vector{ASCIIString})  # names must be an array but that's ok
  function my_iterator()
    for name in names
      produce(CUTEstModel(name))  # like yield in Python
    end
  end
  return Task(my_iterator)
end

# Example usage:
function work_through_stuff(stuff)
  for thing in stuff
    println(thing)
  end
end

work_through_stuff(cutest_problems(["rosenbrock", "hs13", "ncvxqp3"]))
```
The question is: should we continue to support Julia 0.4?

**Comment by abelsiqueira** [comment]
I see, wasn't aware of that way to do it. But I think we should drop 0.4. NLPModels already dropped, and CUTEst will follow.

**Comment by dpo** [comment]
Ok.

**Comment by abelsiqueira** [comment]
[MacroTools.jl 0.3.5](https://github.com/JuliaLang/METADATA.jl/pull/7903) is breaking this (and everything inbetween).

**Pull request merged**
