### PR TITLE
trunk: use operator with preallocation

### PR DESCRIPTION
**Pull request by dpo**
This cuts the total memory allocated by about a factor of 2. It's a safe thing to do with CG.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
What if we create `hess_op!`? Would it make sense?

**Comment by dpo** [comment]
It would, but where do we store the temporary vector? And if a user doesn't use `hess_op!`, we've allocated an `n`-vector for nothing. What's the solution?

**Comment by abelsiqueira** [comment]
`hess_op(nlp, x, temp)`. The user has to create `temp`, like he would for other inplace methods.

**Comment by dpo** [comment]
Ok, that sounds good. Do you want to add that to NLPModels?

**Comment by dpo** [comment]
ps: you can probably do the same in TRON.

**Comment by abelsiqueira** [comment]
Implementend in https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/66

**Comment by dpo** [comment]
Updated.

**Comment by abelsiqueira** [comment]
Thanks

**Pull request merged**
