### PR TITLE
Profiles -> BenchmarkProfiles

### PR DESCRIPTION
**Pull request by dpo**
- on osx, Homebrew.jl should take care of installing cmake when building AmplNLReader
- I really wonder why it's still necessary to link libgfortran on linux. Why isn't that already in the deb?!?!

### CODE REVIEW

**Comment by dpo** [comment]
Requires #24.

**Comment by dpo** [comment]
I removed the dependency on BenchmarkProfiles from the tests because BenchmarkProfiles depends on Plots, which requires Julia ≥ 0.5.

**Comment by dpo** [comment]
The build errors here are due to a recent fix in `sifdecoder` to process the `-force` command-line argument, which is used here in the test. I need to update the git mirrors.

**Comment by dpo** [comment]
I reverted the `-force` test to get this the green light.

**Comment by abelsiqueira** [comment]
Now `AmplNLReader` is also master.

**Comment by abelsiqueira** [comment]
:+1:

**Pull request merged**
