### PR TITLE
Separate benchmark and profile arguments

### PR DESCRIPTION
**Pull request by dpo**
Add documentation to clarify how each function works.

### CODE REVIEW

**Comment by dpo** [comment]
@vepiteski

**Comment by dpo** [comment]
More documentation coming...

**Comment by dpo** [comment]
@abelsiqueira Comments?

**Comment by abelsiqueira** [comment]
Thanks, this improves a lot. Maybe we can make a time profile too?

**Comment by dpo** [comment]
We could. We'd need to take care of the warmup.

**Comment by abelsiqueira** [comment]
Maybe using [BenchmarkTools `tune!`](https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/manual.md)

**Pull request merged**
