### PR TITLE
Pkg.add("NLPModels")

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
There's an issue here because BenchmarkProfiles requires Julia ≥ 0.5.

**Comment by abelsiqueira** [comment]
I think it's ok to drop 0.4 in this package.

**Comment by dpo** [comment]
The profiles are a very small part of this package, so we should think about it. It's Plots.jl that requires 0.5, but now JuMP does the same.

**Comment by abelsiqueira** [comment]
Let's discuss it because 0.6 will probably have a similar problem, and also MPB/JuMP when they update.

A different option would be doing the same we do with MPB (`if Pkg.installed...`).
We would have to test optionally on v0.4 (which is not supported in METADATA, I think), or don't test it, which is not good, as it would be equivalent to dropping.

We could drop BenchmarkProfiles here, and move the benchmark code to another package (change to NLPBenchmark?). Also, this wouldn't fix the JuMP case.

Another option would be dropping Plots, which I don't think is viable, (even though using [perprof-py](https://github.com/ufpr-opt/perprof-py) would make me happy). Also, this wouldn't fix the JuMP case.

**Comment by dpo** [comment]
Strictly speaking, BenchmarkProfiles doesn't need to depend on Plots.jl. In fact, I used to have variants for each plotting package out there! It'd be easy to convert to, say, PyPlot.jl or any other that supports Julia 0.4. Another way to approach the problem is: do we need to support Julia 0.4, or should we just move along and only support 0.5 and up? So far, I've seen pretty substantial speedups with 0.5 compared to 0.4 (you see it in the build times on Travis too).

**Comment by abelsiqueira** [comment]
Since we haven't announced JSO yet, maybe it's the best moment to drop support to 0.4.

**Comment by dpo** [comment]
Do you mean for all packages?

**Comment by abelsiqueira** [comment]
Yes, but we wait for when JuMP changes.

**Comment by dpo** [comment]
Here's a temporary hack to only use BenchmarkProfiles on 0.5. It's not great. Some restructuring is coming.

**Comment by dpo** [comment]
Same error on Linux/0.6:
```
ERROR: LoadError: Cannot clone JuMP from https://github.com/JuliaOpt/JuMP.jl.git. SSL error: ffffffff - UNKNOWN ERROR CODE (0001)
```

**Comment by abelsiqueira** [comment]
We can ignore it; wait for it to be solved; change Travis to `allow_failure`.
I rather not wait.

**Comment by dpo** [comment]
I agree. Let's not wait. We're not claiming to support Julia 0.6 fully anyways. And now the osx builders on Travis are down. Again.

**Comment by dpo** [comment]
This is ready then, I think.

**Comment by abelsiqueira** [comment]
Thank you

**Pull request merged**
